### ISSUE TITLE
Hi, How do I program so I can display results of glow in pangolin gui?

### ISSUE THREAD

**Issue by lfwin** [jbehley/glow#11]
I want to use glow to calculate some results in shader program, then I want to display this results in pangolin. A naive approach is like this, with glow::GlTransformFeedback to get back results from GPU to CPU, then display in pangolin(from CPU to GPU), This consume the time to move data back and forth. So, how do I do so pangolin can display results from glow?

**Comment by jbehley** [comment]
I'm not an Pangolin expert, but as far as I know is Pangolin also a "wrapper" around OpenGL calls; thus, you can maybe directly use the OpenGL handles (i.e., the integers / ids) to buffers, etc. to directly use the already allocated OpenGL resource on the GPU. All glow objects are derived from GlObject and therefore have the id() method to get the id of the corresponding OpenGL object.
