### ISSUE TITLE
How to find the doc?

### ISSUE THREAD

**Issue by zorosmith** [jbehley/glow#7]
Hello, I am learning the SuMa. 
Thank you for your great work! It helps me a lot.
In the source code, you use a lot of API of the glow, which makes me confused.
Could you tell me how to access the doc of the glow?
Thanks!

**Comment by jbehley** [comment]
There is currently no other documentation then the comments in the source code. I tried to provide for all classes a description at the top.

I don't know if I will find time to do a smaller example, but you can see SuMa and the point labeler to see usage examples.

(Sorry for the delay. I'm currently quite busy...)

**Comment by zorosmith** [comment]
Thank you for your hard work!
